language: cpp
os: linux

matrix:
  include:
    - compiler: clang
      dist: bionic

    - compiler: gcc
      dist: xenial
      addons:
        apt:
          sources:
            - sourceline: 'ppa:ubuntu-toolchain-r/test'
          packages:
            - g++-9
      env:
        - CXX=g++-9
        - CXX_FOR_BUILD=g++-9
        - CXXSTD=-std=c++17

script:
  - ${CXX} --version
  - mkdir -p build && cd build
  - cmake -DCMAKE_CXX_COMPILER=${CXX} ..
  - make clean && make -k
  - cd test
  - ctest -V --output-on-failure